applications:
- api_domain: api.dev.jitdev.io
  application_name: '123123'
  authentication_mode: selenium
  exclude_paths: []
  login_page_url: https://platform.dev.jitdev.io/login
  password: encrypted$AQICAHhpFcIXIhU6d93x5dEW8mdH+GAoJET0G2RkVqkI5vH/4QHtPbrskEY89dtPHGKrecK2AAAAdjB0BgkqhkiG9w0BBwagZzBlAgEAMGAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZ9JMbAVYer7Wl0tbAgEQgDNMY6TB2T8Qhb5YiBQwP1bjLhghTHQEENty9i/EAH5n3IF6bmgptHwZRdR4QLHms4anz3Q=
  password_css_selector: input[data-test-id='input-password']
  target_url: https://8ed841b1192c.ngrok.io/swagger.json
  type: api
  username: jit.cypress.e2e.dev@gmail.com
  username_css_selector: input[data-test-id='input-email']
deployment:
  environments:
  - staging
plan_items:
  item-api-security:
    deployment:
      configuration:
      - '123123'
      tags:
      - staging
      trigger: deployment
