applications:
- application_name: google
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://google.com
  type: web
aws:
- account_id: '859000334327'
  regions:
  - us-east-1
  type: account
